---
# Directories to be created in home folder
home_directories:
  - dev
  - docker-apps
  - .bin
  - .rails_template

# git_config:
#   name: <name>
#   email: <email>
git_config: {}

# Docker Containers
docker_apps:
  folder: "{{ansible_env.HOME}}/docker-apps"
  dck_net_name: dck_local_net
  postgres:
    db_user: pg
    db_password: 123456


# Node
# node_config:
#   default_version:
#   yarn_version:
#   versions: []
node_config: {}

# Ruby
# ruby_config:
#   default_version:
#   rails_template_repo: 
#   rails_template_path:
#   versions: []
ruby_config: {}