---
- name: Update apt cache
  apt: update_cache=yes

- name: Install apt dependencies
  apt: name={{ item }}
  with_items:
    - autoconf
    - tar
    - unzip
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - python-pip
    - python-dev
    - htop
    - git	

- name: Install additional packages
  apt: name={{ item }}
  with_items: additional_packages
  when: additional_packages is defined

- stat: path={{ user_home_path }}/.profile
  register: prfl

- name: Create user ~/.profile which loads .bashrc
  template: src=bash_profile.j2 dest={{ user_home_path }}/.profile
  when: prfl.stat.exists == False

- stat: path={{ user_home_path }}/.bashrc
  register: brc

- name: Create user ~/.bashrc which loads .bash_aliases
  template: src=bashrc.j2 dest={{ user_home_path }}/.bashrc
  when: brc.stat.exists == False

- name: Setup ~/.bash_aliases for customs alias
  template: src=bash_aliases.j2 dest={{ user_home_path }}/.bash_aliases

- stat: path={{ user_home_path }}/.gitconfig
  register: gconf

- name: Checking variable git_name 
  fail: msg="This play requires 'git_name', check the group_vars/all/config.yml"
  when: git_name is undefined and gconf.stat.exists is not defined

- name: Checking variable git_email
  fail: msg="This play requires 'git_email', check the group_vars/all/config.yml"
  when: git_email is undefined and gconf.stat.exists is not defined

- name: Create ~/.gitconfig which contains git configurations
  template: src=gitconfig.j2 dest={{ user_home_path }}/.gitconfig
  when: gconf.stat.exists == False

- name: Create ~/.gitconfig.alias which contains git alias
  template: src=gitconfig.alias.j2 dest={{ user_home_path }}/.gitconfig.alias