---
- name: Add alacritty repository from PPA
  become: True
  ansible.builtin.apt_repository:
    repo: ppa:aslatter/ppa
    codename: focal
    update_cache: True

- name: Install terminal dependencies
  become: True
  apt: name={{ item }}
  with_items:
    - alacritty
    - zsh
    - fzf
    - fd-find
    - ripgrep

- name: Install bat tool
  become: True
  apt:
    name: bat
    dpkg_options: 'force-overwrite'

- name: Creating bat symlink
  ansible.builtin.file:
    src: "/usr/bin/batcat"
    dest: "{{ansible_env.HOME}}/.local/bin/bat"
    state: link

- name: Creating fd symlink
  ansible.builtin.file:
    src: "/usr/bin/fdfind"
    dest: "{{ansible_env.HOME}}/.local/bin/fd"
    state: link

- name: Downloading nerd fonts
  ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: ~/.cache/nerd-fonts

- name: Install Meslo font
  ansible.builtin.shell: ./install.sh Meslo
  args:
    chdir: "{{ansible_env.HOME}}/.cache/nerd-fonts"
    executable: /bin/bash
