---
- name: Add alacritty repository from PPA
  become: True
  ansible.builtin.apt_repository:
    repo: ppa:aslatter/ppa
    codename: focal
    update_cache: True

- name: Update apt cache
  become: True
  apt: name=alacritty

- name: Downloading nerd fonts
  ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: ~/.cache/nerd-fonts

- name: Install Meslo font
  ansible.builtin.shell: ./install.sh Meslo
  args:
    chdir: "{{ansible_env.HOME}}/.cache/nerd-fonts"
    executable: /bin/bash

- name: Create alacritty config dir
  file:
    path: ~/.config/alacritty
    state: directory

- name: Copy alacritty config files
  copy:
    src: "{{item}}"
    dest: "~/.config/alacritty/{{item}}"
  with_items:
    - alacritty.yml
    - dracula.yml
